version: '3.9'

services:
  watch-and-run:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - host=db
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=utp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
