db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

db_tables:
  event: event
  launch: launch

path_and_commands:
  - path: /home/user/project1
    commands:
      - go build -o ./build/bin/app1 cmd/service/main.go
      - go run ./build/bin/app1
    include_regexp:
        - .*.go$
        - .*.env$
    exclude_regexp:
          - .*._test.go$
    log_file: /tmp/log2.out
  - path: /home/user/project2
    commands:
      - go test ./...
    include_regexp:
        - .*.go$
        - .*.env$
    exclude_regexp:
          - .*._test.go$
    log_file: /tmp/log2.out
